<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\templates\RuntimeHost.Startup.Minimal.Template.cs.txt" Link="Program.cs" />
    <ProjectReference Include="..\..\Iwesun.Runtime.Data\Iwesun.Runtime.Data.csproj" />
    <ProjectReference Include="..\..\Iwesun.Runtime.Diagnostics\Iwesun.Runtime.Diagnostics.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
  </ItemGroup>
</Project>
