<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <RootNamespace>Iwesun.Runtime.RemoteConsole.Protocol</RootNamespace>
    <AssemblyName>Iwesun.Runtime.RemoteConsole.Protocol</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Data\src\Iwesun.Runtime.Data\Iwesun.Runtime.Data.csproj" />
    <ProjectReference Include="..\..\..\Diagnostics\src\Iwesun.Runtime.Diagnostics\Iwesun.Runtime.Diagnostics.csproj" />
  </ItemGroup>
</Project>
