<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Iwesun.Runtime.WebView2.SampleHost</RootNamespace>
    <AssemblyName>Iwesun.Runtime.WebView2.SampleHost</AssemblyName>
    <Platforms>AnyCPU;x86;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4078.44" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Data\src\Iwesun.Runtime.Data\Iwesun.Runtime.Data.csproj" />
    <ProjectReference Include="..\..\src\Iwesun.Runtime.WebView2\Iwesun.Runtime.WebView2.csproj" />
  </ItemGroup>
</Project>
