<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <IsPackable>false</IsPackable>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>Iwesun.Runtime.Web.WinUI.Tests</AssemblyName>
    <RootNamespace>Iwesun.Runtime.Web.WinUI.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260710003" />
    <PackageReference Include="xunit" Version="2.9.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Iwesun.Runtime.Web\Iwesun.Runtime.Web.csproj" />
    <ProjectReference Include="..\..\src\Iwesun.Runtime.Web.WinUI\Iwesun.Runtime.Web.WinUI.csproj" />
  </ItemGroup>
</Project>
